title: <Change Me>
subtitle: 'Documentation'
description: 'Independent Research Project'
keywords:
author: <Change Me>
language: en
timezone: ''
url: https://wikip.co/<change-me>
root: /<change-me>/
permalink: :post_title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public/<change-me>
tag_dir: tags
archive_dir: archive
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 0
  order_by: -updated
default_category: uncategorized
category_map:
tag_map:
meta_generator: false
date_format: MMMM Do YYYY, h:mm a
time_format: HH:mm:ss
updated_option: 'mtime'
per_page: 0
pagination_dir: page
include:
exclude:
ignore:
theme: replica
deploy:
markdown:
  plugins:
    - markdown-it-footnote
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'
email: me@wikip.co
ipfsurl: http://ipfs.wikip.co/
intro: >
  This site is home to thousands of original research articles.
  Each of the main categories are listed here.
favicon: https://res.cloudinary.com/alchemist-cookbook/image/upload/v1664599773/booksquoosh.png
avatar: https://res.cloudinary.com/alchemist-cookbook/image/upload/v1664599773/booksquoosh.png
social:
  github: https://github.com/wikip-co
sites:
  "bible-study":
    - "Study of the Jewish and Christian Scriptures..."
  "child-development":
    - "Pregnancy, Child Development, Parenting..."
  "current-events":
    - "Technology, Arts, Economy, News..."
  "devops":
    - "DevOps, Cloud Computing, Programming..."
  "modern-history":
    - "From the Late Middle Agest to today..."
  "natural-healing":
    - "Nutrition, Biology, Health..."
